### ISSUE TITLE
`search.toml` doesn't add `SITEURL`  before `url`

### ISSUE THREAD

**Issue by baseplate-admin** [pelican-plugins/search#26]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/pelican-plugins/search/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Windows 11
- **Python version**: 3.11
- **Pelican version**: 4.8.0
- **Version of this plugin**: 1.0.2
- **Link to theme**: https://github.com/aleylara/Papyrus
- **Links to plugins**: https://github.com/baseplate-admin/Blog/tree/main/pelican-plugins/pelican-toc
- **Link to your site**: https://baseplate-admin.github.io/blog/
- **Link to your source**: https://github.com/baseplate-admin/Blog
-->

## Issue

So when indexing with stork i have this file as `search.toml`
```toml
[input]
base_directory = "output"
html_selector = "main"

[[input.files]]
path = "how-i-added-daphne-server-dectection-to-wappalyzer.html"
url = "/how-i-added-daphne-server-dectection-to-wappalyzer.html"
title = "How I added daphne server dectection to wappalyzer"

[[input.files]]
path = "how-i-lost-my-first-pc.html"
url = "/how-i-lost-my-first-pc.html"
title = "How I lost my first PC"

[[input.files]]
path = "how-i-fell-in-love-with-honeyworks.html"
url = "/how-i-fell-in-love-with-honeyworks.html"
title = "How I fell in love with Honeyworks"

[[input.files]]
path = "how-i-fixed-htmx-redeclaration-of-let-element-with-hx-boosttrue.html"
url = "/how-i-fixed-htmx-redeclaration-of-let-element-with-hx-boosttrue.html"
title = "How I fixed htmx redeclaration of let element with hx-boost=true"
```

But if you see my site it is hosted on `https://baseplate-admin.github.io/blog/`

So whenever i search within my site the links all point to `https://baseplate-admin.github.io/` + `filename`

The solution i would like :

Add `SITEURL` before `url` so that the `search.toml` becomes like this : 
```toml
[input]
base_directory = "output"
html_selector = "main"

[[input.files]]
path = "how-i-added-daphne-server-dectection-to-wappalyzer.html"
url = "https://baseplate-admin.github.io/blog//how-i-added-daphne-server-dectection-to-wappalyzer.html"
title = "How I added daphne server dectection to wappalyzer"

[[input.files]]
path = "how-i-lost-my-first-pc.html"
url = "https://baseplate-admin.github.io/blog//how-i-lost-my-first-pc.html"
title = "How I lost my first PC"

[[input.files]]
path = "how-i-fell-in-love-with-honeyworks.html"
url = "https://baseplate-admin.github.io/blog//how-i-fell-in-love-with-honeyworks.html"
title = "How I fell in love with Honeyworks"

[[input.files]]
path = "how-i-fixed-htmx-redeclaration-of-let-element-with-hx-boosttrue.html"
url = "https://baseplate-admin.github.io/blog//how-i-fixed-htmx-redeclaration-of-let-element-with-hx-boosttrue.html"
title = "How I fixed htmx redeclaration of let element with hx-boost=true"
```
